name: 📝 Documentation Issue
description: Report outdated, missing, or unclear documentation.
title: "[Docs]: "
labels: ["documentation"]

body:
  - type: dropdown
    attributes:
      label: Documentation scope
      options:
        - CLI (`ascender` command)
        - Core API
        - Dependency Injection
        - Schematics (`ascender g ...`)
        - Testing / SpecTests
        - Logging / ASC_LOGGER
        - Frontend (if applicable)
        - API reference
        - Other

  - type: input
    attributes:
      label: Page or file path
      placeholder: docs/core/di/overview.md

  - type: textarea
    attributes:
      label: Issue description
      description: What is incorrect, missing, or confusing?

  - type: textarea
    attributes:
      label: Suggested fix or improvement
      description: Write or paste your proposed change or corrected snippet.
